### PR TITLE
IE8 compatibility issue fixed

### PR DESCRIPTION
**Pull request by jca258**
This provides compatibility with IE8, checks for addEventListener existence and replaces it with attachEvent if it isn't defined.

### CODE REVIEW

**Comment by AdamQuadmon** [comment]
@jca258 you didn't like mine? :P

**Comment by AdamQuadmon** [comment]
umm, I see, this is better, mine was just something to make the code not break.

**Comment by tbosch** [comment]
Thanks, will look into this soon!

**Comment by jca258** [comment]
Hi @AdamQuadmon, I was in a hurry trying to solve an issue for a project, I've seen yours when I did the pull request :).

@tbosch thanks for the fill! It helped me a lot!

**Comment by shidhincr** [comment]
Is this not merged still ?

**Comment by odino** [comment]
:+1:

**Comment by tbosch** [comment]
Sorry for the delay, landed.

**Comment by jonkri** [comment]
I would like to see a release with this functionality, so that I can download it through Bower.

**Pull request closed without merging**
